@startuml
title Activity diagram\n

!include ../../plantuml-styles/plantuml-ae-noshadowing.iuml


start



if (Receive Order) then (accepted)
:Fill Order;
:Order Accepted;


fork
:Ship Order;

fork again
:Send Invoice;

:Receive Payment;

end fork

else (Order Rejected)
:Send Order Declined Notice;

endif


:Close Order;

end

!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml