@startuml
title Class diagram
'!include ../../plantuml-styles/plantuml-ae-noshadowing.iuml


abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}


enum TimeUnit {
DAYS
HOURS
MINUTES
}

'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml