@startuml

title Arrows with a color specified

A -[#magenta]>> B:-[#magenta]>> creates a magenta unfilled arrow with a solid line
A --[#939393]>  B:--[#939393]> creates a gray filled arrow with a dashed line
A o-[#blue]>> B:o-[#blue]>> creates a blue, solid line found message
A -[#red]>x B: -[#red]>x creates a red, solid line deletion message

!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml