@startuml

participant "default box" as particpantA

control "control image" as controlC

control "Controller C" as A #lightGreen

controlC -> A

!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml