@startuml

!include plantuml-ae.iuml

'!include ../../plantuml-styles/plantuml-ae.iuml

skinparam Shadowing false


Alice -> Bob: Authentication Request
Bob -> RequestHandler: validated Authenticated Request
RequestHandler --> Bob: Authenticated Response (OK)
Bob --> Alice: Authentication Response (OK)

@enduml