@startuml
'!include ../../plantuml-styles/plantuml-ae.iuml

skinparam ActorBorderColor   SaddleBrown
skinparam NoteFontStyle normal
skinparam Shadowing false


title Usecase Diagrams: Connecting Notes to Objects

(Use the application) as (Use)

User -[#LightSlateGray]-> (Start)
User -[#LightSlateGray]-> (Use)

note "This note is connected to \n two use cases \n and the User actor."  as N2  #white

(Start) <<-[#orange]- N2
N2 .[#magenta].|> (Use)
User <==[#DeepSkyBlue]==> N2

'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml