@startuml
'!include ../../plantuml-styles/plantuml-ae.iuml

skinparam Shadowing false

skinparam ArrowFontStyle normal
skinparam ArrowFontName Courier
skinparam ArrowFontSize 10

title Arrows in Use Case diagrams\n


(Manage Users) -up-|> (Management): This arrow is -up-|>

:All Users:      as allUsers #violet
:Main Admin:     as Admin    #saddleBrown
:User:           as U        #tan
:System Manager: as manager

Admin   -up-|>    allUsers: This arrow is -up->
manager -right-|> allUsers: This arrow is -right-|>
U       -|>       allUsers: This arrow is -|>

Admin --> U:    This arrow is -->
Admin <.....> U: This arrow is <.....>

Admin   -[#blue]->    (Manage Users): This arrow is -[#blue]->
manager -[#blue]->> (Manage Users): This arrow is -[#blue]->>


!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml