@startuml

DocUtilsDirective <|-- SphinxDirective
SphinxDirective <|-- Index

class SphinxDirective {

env(self)
config(self)

}

class Index {
Object[] elementData
run(self) - parse index:: args
}


@enduml