@startuml

title ActivityFontStyle bold
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam ActivityFontStyle bold
!include activity-alarmrings.txt


!include ../../../plantuml-styles/ae-copyright-footer.txt
@enduml