@startuml

title activityDiamondFontName Papyrus
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam activityDiamondFontName Papyrus
!include activity-alarmrings.txt

!include ../../../plantuml-styles/ae-copyright-footer.txt
@enduml