@startuml

title ActivityBackgroundColor lightCyan
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml


skinparam ActivityBackgroundColor lightCyan
!include activity-alarmrings.txt

!include ../../../plantuml-styles/ae-copyright-footer.txt
@enduml