@startuml

title activityDiamondBorderColor red
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml


skinparam activityDiamondBorderColor red
!include activity-alarmrings.txt

!include ../../../plantuml-styles/ae-copyright-footer.txt
@enduml