@startuml
title activityDiamondBackgroundColor GreenYellow
!include ../../../plantuml-styles/plantuml-ae-noshadowing.iuml

skinparam activityDiamondBackgroundColor GreenYellow
!include activity-alarmrings.txt
@enduml