@startuml
title ActivityBorderColor red
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml


skinparam ActivityBorderColor red

'!include activity.txt

!include activity-alarmrings.txt

!include ../../../plantuml-styles/ae-copyright-footer.txt
@enduml