@startuml

title ActivityStartColor aqua
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam ActivityStartColor aqua
!include activity-alarmrings.txt

!include ../../../plantuml-styles/ae-copyright-footer.txt
@enduml