@startuml

title ActivityEndColor Fuchsia
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml


skinparam ActivityEndColor Fuchsia
!include activity-alarmrings.txt

!include ../../../plantuml-styles/ae-copyright-footer.txt
@enduml