@startuml

title ActivityFontName Papyrus
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam ActivityFontName Papyrus
!include activity-alarmrings.txt

!include ../../../plantuml-styles/ae-copyright-footer.txt
@enduml