@startuml
title activityDiamondBackgroundColor GreenYellow
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam activityDiamondBackgroundColor GreenYellow
!include activity-alarmrings.txt

!include ../../../plantuml-styles/ae-copyright-footer.txt
@enduml