@startuml

title ActorStereotypeFontColor red
!include ../../../plantuml-styles/plantuml-ae-noshadowing.iuml

skinparam ActorStereotypeFontColor red

!include usecase-2actors.txt

actor  Tim <<Stereotype text>>

@enduml