@startuml
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam ArtifactStereotypeFontStyle italic

title ArtifactStereotypeFontStyle italic

artifact Artifact <<Stereotype>>

@enduml