@startuml
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam BoundaryStereotypeFontName Papyrus

title BoundaryStereotypeFontName Papyrus

boundary Boundary <<Stereotype>>

@enduml