@startuml

!include plantuml-ae-skinparam-ex.iuml

skinparam CaptionFontName Papyrus

title CaptionFontName Papyrus

!include activity-alarmrings.txt

caption This is the caption for the diagram.

@enduml