@startuml

'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam CaptionFontColor red

title CaptionFontColor red

!include activity-alarmrings.txt

caption This is the caption for the diagram.

@enduml