@startuml
'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam ComponentStereotypeFontStyle italic

title ComponentStereotypeFontStyle italic

component Component <<Stereotype>>
@enduml