@startuml
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam ComponentStereotypeFontColor red

title ComponentStereotypeFontColor red

component Component <<Stereotype>>
@enduml