@startuml
!include ../../../plantuml-styles/plantuml-ae-noshadowing.iuml

skinparam ComponentStereotypeFontName Papyrus

title ComponentStereotypeFontName Papyrus

component Component <<Stereotype>>
@enduml