@startuml
'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam DatabaseStereotypeFontStyle italic

title DatabaseStereotypeFontStyle italic

database Database <<Stereotype>>
@enduml