@startuml

'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam FooterFontColor red

title FooterFontColor red

!include activity-alarmrings.txt

footer This is the footer for the diagram.

@enduml