@startuml

!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam FooterFontName Papyrus

title FooterFontName Papyrus

!include activity-alarmrings.txt

footer This is the footer for the diagram.

@enduml