@startuml

!include plantuml-ae-skinparam-ex.iuml

skinparam Guillemet true

title Guillemet true

participant Alice << Testable >>
participant  Bob << Generated >>

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

@enduml
