@startuml

!include plantuml-ae-skinparam-ex.iuml

skinparam HeaderFontName Papyrus

title HeaderFontName Papyrus

!include activity-alarmrings.txt

header This is the header for the diagram.

@enduml