@startuml
'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam InterfaceFontColor red

title InterfaceFontColor red

component "component Z" as z

interface Interface

z <|- Interface

@enduml