@startuml
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam InterfaceBackgroundColor lawnGreen

title InterfaceBackgroundColor lawnGreen

component "component Z" as z

interface Interface

z <|- Interface

@enduml