@startuml
'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam InterfaceFontSize 18

title InterfaceFontSize 18


component "component Z" as z

interface Interface

z <|- Interface

@enduml