@startuml
!include plantuml-ae-skinparam-ex.iuml

skinparam InterfaceBackgroundColor red

title InterfaceBackgroundColor red

component "component Z" as z

interface Interface

z <|- Interface

@enduml