@startuml
'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam InterfaceBorderColor red

title InterfaceBorderColor red

component "component Z" as z

interface Interface

z <|- Interface

@enduml