@startuml
!include plantuml-ae-skinparam-ex.iuml

skinparam InterfaceStereotypeFontColor red

title InterfaceStereotypeFontColor red\n

interface Interface <<Stereotype>>

component "component Z" as z

z <|- Interface

@enduml