@startuml
'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam InterfaceStereotypeFontName Papyrus

title InterfaceStereotypeFontName Papyrus\n

interface Interface <<Stereotype>>

component "component Z" as z

z <|- Interface

@enduml