@startuml

!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam LegendBorderColor red

title LegendBorderColor red

!include activity-alarmrings.txt

legend
This is the legend for the diagram.
end legend

@enduml