@startuml
title MaxAsciiMessageLength 10

skinparam MaxAsciiMessageLength 10

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml