@startuml

!include plantuml-ae-skinparam-ex.iuml

skinparam ActorBorderColor   SaddleBrown
skinparam ActorBackgroundColor SaddleBrown

skinparam NoteBorderThickness 5

title NoteBorderThickness 5

:Admin: #saddleBrown
actor Admin

note right of Admin : This is a note.

@enduml