@startuml

!include plantuml-ae-skinparam-ex.iuml

skinparam ActorBorderColor   SaddleBrown
skinparam ActorBackgroundColor SaddleBrown

skinparam NoteBackgroundColor white
skinparam NoteShadowing true

title NoteShadowing true

:Admin: #saddleBrown
actor Admin

note right of Admin : This is a note.

@enduml