@startuml

!include plantuml-ae-skinparam-ex.iuml

skinparam ActorBorderColor   SaddleBrown
skinparam ActorBackgroundColor SaddleBrown

skinparam NoteBorderColor red

title NoteBorderColor red

:Admin: #saddleBrown
actor Admin

note right of Admin : This is a note.

@enduml