@startuml

'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam ActorBorderColor   SaddleBrown
skinparam ActorBackgroundColor SaddleBrown

skinparam NoteFontSize 18

title NoteFontSize 18

:Admin: #saddleBrown
actor Admin

note right of Admin : This is a note.

@enduml