@startuml
'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam PackageStereotypeFontStyle italic

title PackageStereotypeFontStyle italic

package Package <<Stereotype>>
@enduml