@startuml
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam ParticipantPadding 200

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response


@enduml