@startuml
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam RectangleStereotypeFontStyle italic

title RectangleStereotypeFontStyle italic

rectangle Rectangle <<Stereotype>>
@enduml