@startuml
'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam RectangleStereotypeFontColor red

title RectangleStereotypeFontColor red

rectangle Rectangle <<Stereotype>>
@enduml