@startuml
!include ../../../plantuml-styles/plantuml-ae-noshadowing.iuml

skinparam RectangleStereotypeFontStyle italic

title RectangleStereotypeFontStyle italic

rectangle Rectangle <<Stereotype>>
@enduml