@startuml
!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam RectangleStereotypeFontName Papyrus

title RectangleStereotypeFontName Papyrus

rectangle Rectangle <<Stereotype>>
@enduml