@startuml
'!include ../../../plantuml-styles/plantuml-ae-skinparam-ex.iuml

skinparam StorageStereotypeFontStyle italic

title StorageStereotypeFontStyle italic

storage Storage <<Stereotype>>
@enduml