@startuml
!include ../../../plantuml-styles/plantuml-ae-noshadowing.iuml

skinparam ComponentStereotypeFontStyle italic

title ComponentStereotypeFontStyle italic

component Component <<Stereotype>>
@enduml