@startuml

skinparam ClassBackgroundColor #Gainsboro
skinparam ClassFontColor #Gainsboro
skinparam ClassBorderColor #Gainsboro

skinparam ClassStereotypeFontSize 0
skinparam CircledCharacterFontSize 0
skinparam CircledCharacterRadius 0
skinparam ClassBorderThickness 0
skinparam Shadowing false

class Dummy

@enduml