@startuml

skinparam ClassBackgroundColor #Fuchsia
skinparam ClassFontColor #Fuchsia
skinparam ClassBorderColor #Fuchsia

skinparam ClassStereotypeFontSize 0
skinparam CircledCharacterFontSize 0
skinparam CircledCharacterRadius 0
skinparam ClassBorderThickness 0
skinparam Shadowing false

class Dummy

@enduml